# fly.toml app configuration file generated for homebase-website on 2025-04-01T18:05:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'homebase-website'
primary_region = 'bos'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
